/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as X402RouteImport } from './routes/x402'
import { Route as LiberclawRouteImport } from './routes/liberclaw'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ApiRouteImport } from './routes/api'
import { Route as IndexRouteImport } from './routes/index'

const X402Route = X402RouteImport.update({
  id: '/x402',
  path: '/x402',
  getParentRoute: () => rootRouteImport,
} as any)
const LiberclawRoute = LiberclawRouteImport.update({
  id: '/liberclaw',
  path: '/liberclaw',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/chat': typeof ChatRoute
  '/liberclaw': typeof LiberclawRoute
  '/x402': typeof X402Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/chat': typeof ChatRoute
  '/liberclaw': typeof LiberclawRoute
  '/x402': typeof X402Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/chat': typeof ChatRoute
  '/liberclaw': typeof LiberclawRoute
  '/x402': typeof X402Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api' | '/chat' | '/liberclaw' | '/x402'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api' | '/chat' | '/liberclaw' | '/x402'
  id: '__root__' | '/' | '/api' | '/chat' | '/liberclaw' | '/x402'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRoute: typeof ApiRoute
  ChatRoute: typeof ChatRoute
  LiberclawRoute: typeof LiberclawRoute
  X402Route: typeof X402Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/x402': {
      id: '/x402'
      path: '/x402'
      fullPath: '/x402'
      preLoaderRoute: typeof X402RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liberclaw': {
      id: '/liberclaw'
      path: '/liberclaw'
      fullPath: '/liberclaw'
      preLoaderRoute: typeof LiberclawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRoute: ApiRoute,
  ChatRoute: ChatRoute,
  LiberclawRoute: LiberclawRoute,
  X402Route: X402Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
