/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as X402RouteImport } from './routes/x402'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as LiberclawRouteImport } from './routes/liberclaw'
import { Route as CliRouteImport } from './routes/cli'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ApiRouteImport } from './routes/api'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthVerifyRouteImport } from './routes/auth.verify'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const X402Route = X402RouteImport.update({
  id: '/x402',
  path: '/x402',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const LiberclawRoute = LiberclawRouteImport.update({
  id: '/liberclaw',
  path: '/liberclaw',
  getParentRoute: () => rootRouteImport,
} as any)
const CliRoute = CliRouteImport.update({
  id: '/cli',
  path: '/cli',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/chat': typeof ChatRoute
  '/cli': typeof CliRoute
  '/liberclaw': typeof LiberclawRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/x402': typeof X402Route
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/verify': typeof AuthVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/chat': typeof ChatRoute
  '/cli': typeof CliRoute
  '/liberclaw': typeof LiberclawRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/x402': typeof X402Route
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/verify': typeof AuthVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/chat': typeof ChatRoute
  '/cli': typeof CliRoute
  '/liberclaw': typeof LiberclawRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/x402': typeof X402Route
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/verify': typeof AuthVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api'
    | '/chat'
    | '/cli'
    | '/liberclaw'
    | '/subscriptions'
    | '/x402'
    | '/auth/callback'
    | '/auth/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api'
    | '/chat'
    | '/cli'
    | '/liberclaw'
    | '/subscriptions'
    | '/x402'
    | '/auth/callback'
    | '/auth/verify'
  id:
    | '__root__'
    | '/'
    | '/api'
    | '/chat'
    | '/cli'
    | '/liberclaw'
    | '/subscriptions'
    | '/x402'
    | '/auth/callback'
    | '/auth/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRoute: typeof ApiRoute
  ChatRoute: typeof ChatRoute
  CliRoute: typeof CliRoute
  LiberclawRoute: typeof LiberclawRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  X402Route: typeof X402Route
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/x402': {
      id: '/x402'
      path: '/x402'
      fullPath: '/x402'
      preLoaderRoute: typeof X402RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liberclaw': {
      id: '/liberclaw'
      path: '/liberclaw'
      fullPath: '/liberclaw'
      preLoaderRoute: typeof LiberclawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli': {
      id: '/cli'
      path: '/cli'
      fullPath: '/cli'
      preLoaderRoute: typeof CliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRoute: ApiRoute,
  ChatRoute: ChatRoute,
  CliRoute: CliRoute,
  LiberclawRoute: LiberclawRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  X402Route: X402Route,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
