name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install pnpm
        uses: pnpm/action-setup@v6
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'
      - name: Install dependencies
        run: pnpm install
      - name: Run ESLint
        run: pnpm run lint

  build:
    name: "Build"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install pnpm
        uses: pnpm/action-setup@v6
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'
      - name: Install dependencies
        run: pnpm install
      - name: Create .env file
        run: |
          echo "VITE_INFERENCE_BACKEND_URL=https://example.org" >> .env
          echo "VITE_THIRDWEB_CLIENT_ID=example" >> .env
          echo "VITE_SOLANA_RPC=https://example.org" >> .env
          echo "VITE_LTAI_BASE_ADDRESS=0x92e1d72210429Ce7eE8a0d64D526D4b9752801FF" >> .env
          echo "VITE_LTAI_SOLANA_ADDRESS=5ooRTqmvm95bHwp4HMo3iszCwsEseY5hksfSa9EDVpBY" >> .env
      - name: Build project
        run: pnpm run build
